Updating to newest standing controller
DAIRLab/dairlib pull request #200
Opened 2020-10-13 19:25 UTC by yangwill

This feature updates the gains for `run_osc_standing_controller` and adds in the options to command different center of mass positions and pelvis orientations using the radio controller.

2020-10-15 16:49 UTC, yangwill commented
There's still an issue where the robot will shake even when it isn't at the edges of the support polygon. Could postpone updating until we fix this.

Might also be worth waiting until we have new gains for the updated model.

2020-10-21 17:36 UTC, yminchen requested changes
Just one comment on the lcm message initialization. The rest looks good to me!

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/200#-:-MKBDpip4kUpKGkC5B_k:bi05j15)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/run_osc_standing_controller.cc, line 266 at r1](https://reviewable.io/reviews/dairlab/dairlib/200#-MKBDMxV2swMLTJkRMmt:-MKBDMxW76aawP3rQhbi:b-6y447e) ([raw file](https://github.com/dairlab/dairlib/blob/5c570dfb723324f5cf5a99834b44b8e4e9548a48/examples/Cassie/run_osc_standing_controller.cc#L266)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>   //   Get context and initialize the input port of LcmSubsriber for
>   //   lcmt_target_standing_height
>   auto diagram_ptr = loop.get_diagram();
>   auto& diagram_context = loop.get_diagram_mutable_context();
>   auto& target_receiver_context = diagram_ptr->GetMutableSubsystemContext(
>       *target_height_receiver, &diagram_context);
>   //   Note that currently the LcmSubscriber stores the lcm message in the first
>   //   state of the leaf system (we hard coded index 0 here)
>   auto& mutable_state =
>       target_receiver_context
>           .get_mutable_abstract_state<dairlib::lcmt_target_standing_height>(0);
>   dairlib::lcmt_target_standing_height initial_message;
>   initial_message.target_height = FLAGS_height;
>   mutable_state = initial_message;
>   //   Run lcm-driven simulation
> ```
</details>


We should keep this code. I tested in the simulation and was able to initialize the lcm message with this. 


<!-- Sent from Reviewable.io -->

2020-10-21 18:06 UTC, yangwill reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/200)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @yminchen)

___
*[examples/Cassie/run_osc_standing_controller.cc, line 266 at r1](https://reviewable.io/reviews/dairlab/dairlib/200#-MKBDMxV2swMLTJkRMmt:-MKBKgcH6wL2CZKKEnJf:b-yewms9) ([raw file](https://github.com/dairlab/dairlib/blob/5c570dfb723324f5cf5a99834b44b8e4e9548a48/examples/Cassie/run_osc_standing_controller.cc#L266)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> ```
>   //   Get context and initialize the input port of LcmSubsriber for
>   //   lcmt_target_standing_height
>   auto diagram_ptr = loop.get_diagram();
>   auto& diagram_context = loop.get_diagram_mutable_context();
>   auto& target_receiver_context = diagram_ptr->GetMutableSubsystemContext(
>       *target_height_receiver, &diagram_context);
>   //   Note that currently the LcmSubscriber stores the lcm message in the first
>   //   state of the leaf system (we hard coded index 0 here)
>   auto& mutable_state =
>       target_receiver_context
>           .get_mutable_abstract_state<dairlib::lcmt_target_standing_height>(0);
>   dairlib::lcmt_target_standing_height initial_message;
>   initial_message.target_height = FLAGS_height;
>   mutable_state = initial_message;
>   //   Run lcm-driven simulation
> ```

We should keep this code. I tested in the simulation and was able to initialize the lcm message with this. 
</blockquote></details>

The default height is now handled in `standing_com_traj.cc`


<!-- Sent from Reviewable.io -->

2020-10-22 03:24 UTC, yminchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/200#-:-MKDKYc80JR-ffSe_Nh3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yminchen)



<!-- Sent from Reviewable.io -->

2020-10-22 14:54 UTC, merged