Add collocation slack forces DirconTrajectory object
DAIRLab/dairlib pull request #228
Opened 2021-01-31 20:37 UTC by ShaneRozenLevy

The goal of this modification is to make it easier to change the number of knot points when loading a trajectory and using it as the initial guess for another trajopt problem. By working in trajectories/splines you can re-interpolate to increase and decrease the number of knot points.

I add the collocation slack variables to the DirconTrajectory trajectory object while also adding functions which return a vector of trajectories for the contact forces, collocation forces, and collocation slack variables.

This code was initially developed for kod*lab's work on spirit, but it sounds like y'all might find it useful.

2021-02-01 01:30 UTC, yangwill requested changes
Looks great! Is the code used to reconstruct initial guesses for `x`, `u`, `lambda` etc given `n` knotpoints easy to turn into a PR. It might be worth adding if it's not too much work/if it fits well with this current set up because otherwise there don't see to be a clear use for reconstructing trajectories for the slack variables.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/228#-:-MSQBwya0jAxMO2ikXWI:b-jx6jaf)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShaneRozenLevy)

___
*[lcm/dircon_saved_trajectory.h, line 52 at r1](https://reviewable.io/reviews/dairlab/dairlib/228#-MSQ9O8j9F-2uuNsXG8t:-MSQ9O8l-vVntYAY5qxy:b87vebw) ([raw file](https://github.com/dairlab/dairlib/blob/7edb30a3c911570bb25de915a3398658e49f7e0b/lcm/dircon_saved_trajectory.h#L52)):*
> ```objc
>   drake::trajectories::PiecewisePolynomial<double> ReconstructStateTrajectory()
>       const;
>   std::vector<drake::trajectories::PiecewisePolynomial<double>> ReconstructLambdaTrajectory()
> ```

Because the force and slack variables are not true trajectories, it may be clearer if there's comment explaining the purposes of these methods. ie. to make linear interpolation easier.


<!-- Sent from Reviewable.io -->

2021-02-01 04:48 UTC, ShaneRozenLevy commented
> Looks great! Is the code used to reconstruct initial guesses for `x`, `u`, `lambda` etc given `n` knotpoints easy to turn into a PR. It might be worth adding if it's not too much work/if it fits well with this current set up because otherwise there don't see to be a clear use for reconstructing trajectories for the slack variables.
> 
> > Reviewed 1 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/228#-:-MSQBwya0jAxMO2ikXWI:b-jx6jaf)_ status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShaneRozenLevy)
> 
> _[lcm/dircon_saved_trajectory.h, line 52 at r1](https://reviewable.io/reviews/dairlab/dairlib/228#-MSQ9O8j9F-2uuNsXG8t:-MSQ9O8l-vVntYAY5qxy:b87vebw) ([raw file](https://github.com/dairlab/dairlib/blob/7edb30a3c911570bb25de915a3398658e49f7e0b/lcm/dircon_saved_trajectory.h#L52)):_
> 
> > ```objc
> >   drake::trajectories::PiecewisePolynomial<double> ReconstructStateTrajectory()
> >       const;
> >   std::vector<drake::trajectories::PiecewisePolynomial<double>> ReconstructLambdaTrajectory()
> > ```
> 
> Because the force and slack variables are not true trajectories, it may be clearer if there's comment explaining the purposes of these methods. ie. to make linear interpolation easier.



> Looks great! Is the code used to reconstruct initial guesses for `x`, `u`, `lambda` etc given `n` knotpoints easy to turn into a PR. It might be worth adding if it's not too much work/if it fits well with this current set up because otherwise there don't see to be a clear use for reconstructing trajectories for the slack variables.
> 
> > Reviewed 1 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/228#-:-MSQBwya0jAxMO2ikXWI:b-jx6jaf)_ status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ShaneRozenLevy)
> 
> _[lcm/dircon_saved_trajectory.h, line 52 at r1](https://reviewable.io/reviews/dairlab/dairlib/228#-MSQ9O8j9F-2uuNsXG8t:-MSQ9O8l-vVntYAY5qxy:b87vebw) ([raw file](https://github.com/dairlab/dairlib/blob/7edb30a3c911570bb25de915a3398658e49f7e0b/lcm/dircon_saved_trajectory.h#L52)):_
> 
> > ```objc
> >   drake::trajectories::PiecewisePolynomial<double> ReconstructStateTrajectory()
> >       const;
> >   std::vector<drake::trajectories::PiecewisePolynomial<double>> ReconstructLambdaTrajectory()
> > ```
> 
> Because the force and slack variables are not true trajectories, it may be clearer if there's comment explaining the purposes of these methods. ie. to make linear interpolation easier.

I think dircon already has that code. Here is how I currently set my initial guess:
```
    trajopt.drake::systems::trajectory_optimization::MultipleShooting::
        SetInitialTrajectory(u_traj, x_traj);
    for (int j = 0; j < sequence.num_modes(); j++) {
      trajopt.SetInitialForceTrajectory(j, l_traj[j], lc_traj[j],
                                        vc_traj[j]);
    }

```

Where `u_traj`, `x_traj`, `l_traj`, `lc_traj`, and `vc_traj` are all directly returned from the DirconTrajectory object.

2021-02-01 19:07 UTC, yangwill approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/228#-:-MSTzRuU8k2eBlgD1WhF:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yangwill)



<!-- Sent from Reviewable.io -->

2021-02-04 19:01 UTC, yangwill commented
Merging this into master

2021-02-04 19:02 UTC, merged