Impact invariant examples
DAIRLab/dairlib pull request #232
Opened 2021-03-11 19:16 UTC by yangwill

Adding an examples folder to showcase the impact invariant controller. Includes a `.pmd` file that contains all the relevant scripts as well as a README in `examples/impact_invariant_control` that gives brief instructions on how to build and run the examples.

May still make minor changes to the PR such as better documentation and code readability.

2021-03-16 20:12 UTC, yangwill commented
List of common libraries that require a close read through:
- `operational_space_control.h/cc`
- `osc_tracking_data.h/cc`
- `time_based_fsm.h/cc`
- `dircon_saved_trajectory.h/cc`
- `jumping_event_based_fsm.h/cc`
- `run_osc_jumping_controller.cc`

The rest of the files are the simulator/urdf/gains. Though if you have more time, I would prioritize the trajectory generator leaf systems in `examples/Cassie/osc_jump/`

2021-03-17 11:13 UTC, yminchen requested changes
First pass. This PR is quite big. I will review it piece by piece

> Reviewed 18 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232#-:-MVzsWYRAzHkeHFueBAB:bu6ttf9)* status: 18 of 51 files reviewed, 4 unresolved discussions (waiting on @yangwill)

___
*[examples/Cassie/multibody_sim_init.cc, line 45 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVzjO8cEUzMEZGpem8-:-MVzjO8cEUzMEZGpem80:brkd2ci) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/multibody_sim_init.cc#L45)):*
> ```cpp
> 
> namespace dairlib {
> ```

Could you add a documentation here showing the difference between this `multibody_sim_init` and `multibody_sim`? I can see there is platform, so maybe make the filename more specific like multibody_sim_platform?
___
*[examples/Cassie/run_dircon_jumping.cc, line 560 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVzl2H751lIXO8ND-GF:-MVzl2H84-GV5rRFYfuw:b-ucjy5q) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/run_dircon_jumping.cc#L560)):*
> ```cpp
>   MatrixXd Q = 0.1 * MatrixXd::Identity(n_v, n_v);
>   MatrixXd R = 0.005 * MatrixXd::Identity(n_u, n_u);
>   Q(0, 0) = 5;
> ```

nitpick: we can just declare `MatrixXd Q = 5 * MatrixXd::Identity(n_v, n_v);` 
___
*[examples/Cassie/osc_jump/flight_foot_traj_generator.cc, line 77 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVzoew65JE7RX8AEBSF:-MVzoew65JE7RX8AEBSG:b7delmt) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/osc_jump/flight_foot_traj_generator.cc#L77)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     std::vector<double> breaks = foot_traj_segment.get_segment_times();
>     VectorXd breaks_vector = Map<VectorXd>(breaks.data(), breaks.size());
>     MatrixXd hip_points(3, 2);
>     // Velocity estimates are generally bad
>     hip_points << hip_pos, hip_pos;
>     PiecewisePolynomial<double> hip_offset =
>         PiecewisePolynomial<double>::ZeroOrderHold(breaks_vector, hip_points);
> ```
</details>

`hip_offset` seems to be a constant traj. If so, we can construct it in a simpler way: https://drake.mit.edu/doxygen_cxx/classdrake_1_1trajectories_1_1_piecewise_polynomial.html#a838cb1725eb9ba7896158fa9032ecdcc
___
*[examples/Cassie/osc_jump/basic_trajectory_passthrough.cc, line 10 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVznK6c1HPX9D00nzb2:-MVznK6c1HPX9D00nzb3:b-xogrlq) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/osc_jump/basic_trajectory_passthrough.cc#L10)):*
> ```cpp
> namespace dairlib::examples::osc_jump {
> 
> BasicTrajectoryPassthrough::BasicTrajectoryPassthrough(
> ```

Looks like this class can be replaced by Drake's `ConstantValueSource`?


<!-- Sent from Reviewable.io -->

2021-03-20 19:07 UTC, yminchen requested changes
More progress.

> Reviewed 25 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232#-:-MWG0fLF7ogm7O49QdVc:b-tbrtvp)* status: 43 of 51 files reviewed, 11 unresolved discussions (waiting on @yangwill)

___
*[examples/Cassie/run_osc_jumping_controller.cc, line 205 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWEzHig6lY-i701lOaN:-MWEzHig6lY-i701lOaO:bnsxekf) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/run_osc_jumping_controller.cc#L205)):*
> ```cpp
>   // This actually outputs the target position of the pelvis not the true
>   // center of mass
>   auto com_traj_generator = builder.AddSystem<PelvisTransTrajGenerator>(
> ```

I think we should name the variables according to what they are. If it's pelvis/com, then we should use pelvis/com in the name to avoid confusion.  
___
*[examples/impact_invariant_control/five_link_biped_sim.cc, line 70 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWF02wQC24Ap5opmQXE:-MWF02wQC24Ap5opmQXF:b-vbz8qq) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/five_link_biped_sim.cc#L70)):*
> ```cpp
>               "Initial velocity error of the swing leg in global coordinates.");
> 
> VectorXd calcStateOffset(MultibodyPlant<double>& plant,
> ```

nitpick -- code style here should be CalcStateOffset.
Sorry for the nitpicking, but I think the code merged to the master should follow the same code style. 
___
*[examples/impact_invariant_control/five_link_biped_sim.cc, line 72 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWF0FTFB5HA_uc5G9Mo:-MWF0FTGEbOY8cHGO-N0:bf8balg) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/five_link_biped_sim.cc#L72)):*
> ```cpp
> VectorXd calcStateOffset(MultibodyPlant<double>& plant,
>                          Context<double>& context, VectorXd& x0);
> int do_main(int argc, char* argv[]) {
> ```

diddo above, DoMain.
There are other places (other files) where the code style is not consistent (e.g. calcStateOffset), so please check if you have time.
___
*[examples/impact_invariant_control/impact_aware_time_based_fsm.h, line 14 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWFxMvp53oQgnnj3Xl-:-MWFxMvq20CHdgLkRxjB:b-ruxlyo) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/impact_aware_time_based_fsm.h#L14)):*
> ```objc
> 
> enum BLEND_FUNC { SIGMOID, EXP };
> ```

Could you add a short description of what this class is doing? It looks like the new features are independent of the parent class'. If this is the case, we should probably make it a class on its own.
___
*[examples/impact_invariant_control/joint_space_walking_gains.h, line 6 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWFyhLT9Ja0FM99qUqo:-MWFyhLT9Ja0FM99qUqp:b-ntjafw) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/joint_space_walking_gains.h#L6)):*
> ```objc
> using Eigen::MatrixXd;
> 
> struct JointSpaceWalkingGains {
> ```

Just double checking, are the walking gains added by accident? I thought there is only jumping in this PR.
___
*[examples/impact_invariant_control/run_dircon_walking.cc, line 1 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWFzWkI3rNM9VMBZ1zb:-MWFzWkI3rNM9VMBZ1zc:br4qqa2) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/run_dircon_walking.cc#L1)):*
> ```cpp
> #include <chrono>
> ```

Just double checking again, did you intend to add this and `run_joint_space_walking_controller.cc` to impact_invariant_control?
___
*[multibody/multibody_utils.cc, line 342 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWG-ZI_Bq7yuIFD19eI:-MWG-ZI_Bq7yuIFD19eJ:b-dqmb7e) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/multibody/multibody_utils.cc#L342)):*
> ```cpp
> 
> template <typename T>
> Eigen::MatrixXd createWithSpringsToWithoutSpringsMap(
> ```

Can we split this function into two, one for position and one for velocity? It's probably more computationally efficient this way because the matrix is sparse (block diagonal).


<!-- Sent from Reviewable.io -->

2021-03-23 12:24 UTC, yminchen requested changes
> Reviewed 8 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232)* status: all files reviewed, 23 unresolved discussions (waiting on @yangwill)

___
*[lcm/dircon_saved_trajectory.cc, line 262 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWToiw2CdEWONfzZUW7:-MWToiw2CdEWONfzZUW8:b-7rp5nt) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/lcm/dircon_saved_trajectory.cc#L262)):*
> ```cpp
> PiecewisePolynomial<double> DirconTrajectory::ReconstructJointTrajectory(int joint_idx)
> const {
>   PiecewisePolynomial<double> state_traj =
> ```

I think we can construct an empty pp first and then concatenate from mode = 0 instead of 1 in the for loop below.
https://github.com/RobotLocomotion/drake/blob/b09e40db4b1c01232b22f7705fb98aa99ef91f87/common/trajectories/piecewise_polynomial.cc#L303
___
*[systems/controllers/time_based_fsm.cc, line 46 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTq8Ri-vCwVcT-JpVB:-MWTq8Ri-vCwVcT-JpVC:bfhyaq4) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/time_based_fsm.cc#L46)):*
> ```cpp
>   auto current_sim_time = static_cast<double>(robot_output->get_timestamp());
> 
>   //  double m = floor((current_sim_time - t0_) / period_);
> ```

The outdated code can be removed.
___
*[systems/controllers/time_based_fsm.cc, line 56 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTpxDdB0wi-TFjWJe9:-MWTpxDdB0wi-TFjWJeA:b-h5sp1j) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/time_based_fsm.cc#L56)):*
> ```cpp
>       if (remainder < accu_state_durations_[i]) {
>         //        current_finite_state << states_[i];
>         current_finite_state(0) = states_[i];
> ```

Is there a difference between `current_finite_state << states_[i];` and `current_finite_state(0) = states_[i];`?
___
*[systems/controllers/osc/operational_space_control.h, line 127 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTrbVa9CtNLHDQ9c_D:-MWTrbVa9CtNLHDQ9c_E:buxkyvd) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.h#L127)):*
> ```objc
>       return this->get_input_port(traj_name_to_port_index_map_.at(name));
>     }catch(std::exception& e){
>       std::cerr << "Cannot find tracking data named: " << name << std::endl;
> ```

It's probably a good idea to stop the program when there is no matching port name. This would inform the user right away as oppose to having the user to find the issue caused by this missing port.
___
*[systems/controllers/osc/operational_space_control.cc, line 443 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWU-MpKDwtEwIdIe_J0:-MWU-MpL-oEclcKydB-9:b8jf1zm) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L443)):*
> ```cpp
>     const VectorXd& x_w_spr, const VectorXd& x_wo_spr,
>     const drake::systems::Context<double>& context, double t, int fsm_state,
>     double time_since_last_state_switch, double alpha,
> ```

The variable name `alpha` is inconsistent between the method declaration and the method definition
___
*[systems/controllers/osc/operational_space_control.cc, line 600 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTy9FjExI9Y6RLtV3n:-MWTy9FjExI9Y6RLtV3o:b-35oyw3) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L600)):*
> ```cpp
>   bool near_impact = alpha != 0;
>   if (near_impact) {
>     auto map_iterator = contact_indices_map_.find(next_fsm_state);
> ```

Is it possible to move this block of code into a method? It'll improve readability.
___
*[systems/controllers/osc/operational_space_control.cc, line 621 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTzOoi0-Ch7IFvri3G:-MWTzOoi0-Ch7IFvri3H:bqlpol2) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L621)):*
> ```cpp
>       J_c_next.block(row_start, 0, n_h_, n_v_) = J_h;
>     }
>     M_Jt_ = M.inverse() * J_c_next.transpose();
> ```

Inverse is not necessary here. I believe linear solve is faster and probably more accurate. 
___
*[systems/controllers/osc/operational_space_control.cc, line 674 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTxl3AAGeQDhw2eTJY:-MWTxl3AAGeQDhw2eTJZ:b-tszi31) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L674)):*
> ```cpp
>     if (near_impact && tracking_data->IsActive()) {
>       // Need to call Update before this to get the updated jacobian
>       v_proj = alpha * M_Jt_ * ii_lambda_sol_;
> ```

This can probably be moved outside the for-loop?
___
*[systems/controllers/osc/operational_space_control.cc, line 908 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWU1UYUAKir6O1bspHI:-MWU1UYV2dsaSJH1Yzhg:b-a4dlfl) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L908)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     const BasicVector<double>* near_impact =
>         (BasicVector<double>*)this->EvalVectorInput(context, near_impact_port_);
>     VectorXd fsm_state = fsm_output->get_value();
>     // Get discrete states
>     const auto prev_event_time =
>         context.get_discrete_state(prev_event_time_idx_).get_value();
>     u_sol = SolveQp(x_w_spr, x_wo_spr, context, current_time, fsm_state(0),
>                     current_time - prev_event_time(0),
>                     near_impact->get_value()(0), near_impact->get_value()(1));
> ```
</details>


Are we forced to connect OSC with a `near_impact` leafsystem no matter whether we are using impact invariant or not?
___
*[systems/controllers/osc/osc_tracking_data.cc, line 74 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTvsEr3dfrrbKvmpYD:-MWTvsEs6P0o44oNSxkH:b-dcbhvk) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/osc_tracking_data.cc#L74)):*
> ```cpp
>     // Update feedback output (Calling virtual methods)
>     UpdateYAndError(x_w_spr, context_w_spr);
>     UpdateYdotAndError(x_w_spr, context_w_spr, v_proj);
> ```

I don't like how the derived classes' `UpdateYdotAndError` are forced to use `v_proj`. 
Maybe we can add a boolean member `impact_invariant_projection_` (with a public setter) to `OscTrackingData`, and in line 74 here we add 
```
if (impact_invariant_projection_)
  error_ydot_ -= GetJ() * v_proj;
` ``
```

___
*[systems/controllers/osc/osc_tracking_data.cc, line 80 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTtIDk06v5wm37uDWf:-MWTtIDk06v5wm37uDWg:b-8g4h24) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/osc_tracking_data.cc#L80)):*
> ```cpp
> 
>     // Update command output (desired output with pd control)
>     //    yddot_command_ = K_p_ * (error_y_) + K_d_ * (error_ydot_);
> ```

Dead code
___
*[systems/controllers/osc/osc_tracking_data.cc, line 348 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTuv1fA3KfhWoFUdIT:-MWTuv1fA3KfhWoFUdIU:b-g2r9cu) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/osc_tracking_data.cc#L348)):*
> ```
>   error_ydot_ = w_des_ - ydot_ - J_spatial.block(0, 0, kSpaceDim, J_spatial.cols()) * v_proj;
> ```
This line is longer than 80 characters


<!-- Sent from Reviewable.io -->

2021-03-23 12:25 UTC, yminchen reviewed
First pass.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232#-:-MWU1u19-oKzSCZ_pnQX:b-xepgfs)* status: all files reviewed, 23 unresolved discussions (waiting on @yangwill)



<!-- Sent from Reviewable.io -->

2021-04-06 20:32 UTC, yangwill reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232)* status: all files reviewed, 23 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[examples/Cassie/multibody_sim_init.cc, line 45 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVzjO8cEUzMEZGpem8-:-MXclAx4EJIdkVW_v3Yi:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/multibody_sim_init.cc#L45)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Could you add a documentation here showing the difference between this `multibody_sim_init` and `multibody_sim`? I can see there is platform, so maybe make the filename more specific like multibody_sim_platform?
</blockquote></details>

Done.
___
*[examples/Cassie/run_dircon_jumping.cc, line 560 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVzl2H751lIXO8ND-GF:-MXclF0H6J0jm_644Z1a:b-2nlhll) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/run_dircon_jumping.cc#L560)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

nitpick: we can just declare `MatrixXd Q = 5 * MatrixXd::Identity(n_v, n_v);` 
</blockquote></details>

This is just modifying the first 3 diagonal elements of Q. I could set it using block, but I thought this would be easier.
___
*[examples/Cassie/run_osc_jumping_controller.cc, line 205 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWEzHig6lY-i701lOaN:-MXcmIX70U4d1ElLKSmE:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/run_osc_jumping_controller.cc#L205)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

I think we should name the variables according to what they are. If it's pelvis/com, then we should use pelvis/com in the name to avoid confusion.  
</blockquote></details>

Done.
___
*[examples/Cassie/osc_jump/flight_foot_traj_generator.cc, line 77 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVzoew65JE7RX8AEBSF:-MXcr_gh5vaECmM2EUuQ:b-z2qfrq) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/osc_jump/flight_foot_traj_generator.cc#L77)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> ```
>     std::vector<double> breaks = foot_traj_segment.get_segment_times();
>     VectorXd breaks_vector = Map<VectorXd>(breaks.data(), breaks.size());
>     MatrixXd hip_points(3, 2);
>     // Velocity estimates are generally bad
>     hip_points << hip_pos, hip_pos;
>     PiecewisePolynomial<double> hip_offset =
>         PiecewisePolynomial<double>::ZeroOrderHold(breaks_vector, hip_points);
> ```
`hip_offset` seems to be a constant traj. If so, we can construct it in a simpler way: https://drake.mit.edu/doxygen_cxx/classdrake_1_1trajectories_1_1_piecewise_polynomial.html#a838cb1725eb9ba7896158fa9032ecdcc
</blockquote></details>

The issue with setting a constant trajectory is that the segment times must be equal, which is what I'm doing in that code. Otherwise, you run into the error `Addition not yet implemented when segment times are not equal`.
___
*[examples/impact_invariant_control/five_link_biped_sim.cc, line 70 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWF02wQC24Ap5opmQXE:-MXcs1ZrBPsjHWLt7V2V:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/five_link_biped_sim.cc#L70)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

nitpick -- code style here should be CalcStateOffset.
Sorry for the nitpicking, but I think the code merged to the master should follow the same code style. 
</blockquote></details>

Done.
___
*[examples/impact_invariant_control/five_link_biped_sim.cc, line 72 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWF0FTFB5HA_uc5G9Mo:-MXcs1vdC9spgdkWQzQJ:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/five_link_biped_sim.cc#L72)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

diddo above, DoMain.
There are other places (other files) where the code style is not consistent (e.g. calcStateOffset), so please check if you have time.
</blockquote></details>

Done.
___
*[examples/impact_invariant_control/impact_aware_time_based_fsm.h, line 14 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWFxMvp53oQgnnj3Xl-:-MXcsD8q18cKPiV3fR_t:bmw0yp5) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/impact_aware_time_based_fsm.h#L14)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Could you add a short description of what this class is doing? It looks like the new features are independent of the parent class'. If this is the case, we should probably make it a class on its own.
</blockquote></details>

Are you referring to the BLEND_FUNC or  ImpactTimeBasedFiniteStateMachine? This FSM just adds an output port to the timebasedfsm, which is why I am extending it rather than creating a completely separate class.
___
*[examples/impact_invariant_control/joint_space_walking_gains.h, line 6 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWFyhLT9Ja0FM99qUqo:-MXcsYYj9eUqcB97cuMf:bfrlrl) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/joint_space_walking_gains.h#L6)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Just double checking, are the walking gains added by accident? I thought there is only jumping in this PR.
</blockquote></details>

I also included the five-link-biped in the paper, which is why I'm adding this.
___
*[examples/impact_invariant_control/run_dircon_walking.cc, line 1 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWFzWkI3rNM9VMBZ1zb:-MXcsgehCJo5pAHsiVOD:b2nhswv) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/impact_invariant_control/run_dircon_walking.cc#L1)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Just double checking again, did you intend to add this and `run_joint_space_walking_controller.cc` to impact_invariant_control?
</blockquote></details>

Yep


<!-- Sent from Reviewable.io -->

2021-04-06 20:32 UTC, yangwill reviewed
still working on addressing comments, not ready for second pass yet.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232#-:-MXcsmKG6dLDZb1nVm0-:bhpsvvz)* status: all files reviewed, 23 unresolved discussions (waiting on @yangwill and @yminchen)



<!-- Sent from Reviewable.io -->

2021-04-07 03:09 UTC, yangwill reviewed
more responses, still a work in progress.

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232#-:-MXeIZInEfeZLmSsABHo:b-k7njhe)* status: all files reviewed, 23 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[systems/controllers/time_based_fsm.cc, line 46 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTq8Ri-vCwVcT-JpVB:-MXeDOse0dsnIAjhbNcE:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/time_based_fsm.cc#L46)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

The outdated code can be removed.
</blockquote></details>

Done.
___
*[systems/controllers/time_based_fsm.cc, line 56 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTpxDdB0wi-TFjWJe9:-MXeDMQt3iWob9SnMsx4:bkup41k) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/time_based_fsm.cc#L56)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Is there a difference between `current_finite_state << states_[i];` and `current_finite_state(0) = states_[i];`?
</blockquote></details>

nope, reverting back
___
*[systems/controllers/osc/operational_space_control.h, line 127 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTrbVa9CtNLHDQ9c_D:-MXeDw7y4uEhdK2h4LgO:b-keb4gp) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.h#L127)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

It's probably a good idea to stop the program when there is no matching port name. This would inform the user right away as oppose to having the user to find the issue caused by this missing port.
</blockquote></details>

We can definitely stop the program as well, before it would be a segfault instead of a more informative error message.
___
*[systems/controllers/osc/operational_space_control.cc, line 443 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWU-MpKDwtEwIdIe_J0:-MXeEJSr8bH-pmEDfj1u:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L443)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

The variable name `alpha` is inconsistent between the method declaration and the method definition
</blockquote></details>

Done.
___
*[systems/controllers/osc/operational_space_control.cc, line 600 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTy9FjExI9Y6RLtV3n:-MXeFPuf13W4i0a66wuk:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L600)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Is it possible to move this block of code into a method? It'll improve readability.
</blockquote></details>

Done.
___
*[systems/controllers/osc/operational_space_control.cc, line 621 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTzOoi0-Ch7IFvri3G:-MXeHRVE6IxdJRu2kaK8:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L621)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Inverse is not necessary here. I believe linear solve is faster and probably more accurate. 
</blockquote></details>

Done.
___
*[systems/controllers/osc/operational_space_control.cc, line 674 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTxl3AAGeQDhw2eTJY:-MXeI1YJ2LZbLBuOFdOJ:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L674)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

This can probably be moved outside the for-loop?
</blockquote></details>

Done.
___
*[systems/controllers/osc/osc_tracking_data.cc, line 80 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTtIDk06v5wm37uDWf:-MXeITZJEOM-Ca4S7wBW:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/osc_tracking_data.cc#L80)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Dead code
</blockquote></details>

Done.
___
*[systems/controllers/osc/osc_tracking_data.cc, line 348 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTuv1fA3KfhWoFUdIT:-MXeISgn2b9EEo1JwqbZ:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/osc_tracking_data.cc#L348)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> ```
>   error_ydot_ = w_des_ - ydot_ - J_spatial.block(0, 0, kSpaceDim, J_spatial.cols()) * v_proj;
> ```
This line is longer than 80 characters
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-07 17:04 UTC, yangwill reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232)* status: all files reviewed, 23 unresolved discussions (waiting on @yminchen)

___
*[lcm/dircon_saved_trajectory.cc, line 262 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWToiw2CdEWONfzZUW7:-MXgwNI02obAVuHEoe79:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/lcm/dircon_saved_trajectory.cc#L262)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

I think we can construct an empty pp first and then concatenate from mode = 0 instead of 1 in the for loop below.
https://github.com/RobotLocomotion/drake/blob/b09e40db4b1c01232b22f7705fb98aa99ef91f87/common/trajectories/piecewise_polynomial.cc#L303
</blockquote></details>

Done.
___
*[multibody/multibody_utils.cc, line 342 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWG-ZI_Bq7yuIFD19eI:-MXh4pqp2RLsY_PJZnkT:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/multibody/multibody_utils.cc#L342)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Can we split this function into two, one for position and one for velocity? It's probably more computationally efficient this way because the matrix is sparse (block diagonal).
</blockquote></details>

Done.
___
*[systems/controllers/osc/operational_space_control.cc, line 908 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWU1UYUAKir6O1bspHI:-MXhG0Sy9KYKXyqlL1X3:bmjtuvl) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/operational_space_control.cc#L908)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> ```
>     const BasicVector<double>* near_impact =
>         (BasicVector<double>*)this->EvalVectorInput(context, near_impact_port_);
>     VectorXd fsm_state = fsm_output->get_value();
>     // Get discrete states
>     const auto prev_event_time =
>         context.get_discrete_state(prev_event_time_idx_).get_value();
>     u_sol = SolveQp(x_w_spr, x_wo_spr, context, current_time, fsm_state(0),
>                     current_time - prev_event_time(0),
>                     near_impact->get_value()(0), near_impact->get_value()(1));
> ```

Are we forced to connect OSC with a `near_impact` leafsystem no matter whether we are using impact invariant or not?
</blockquote></details>

I changed it so that if `near_impact_port` isn't connected, it won't use the projection.
___
*[systems/controllers/osc/osc_tracking_data.cc, line 74 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MWTvsEr3dfrrbKvmpYD:-MXh7Laq26_wQNliUp7a:bv8snew) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/systems/controllers/osc/osc_tracking_data.cc#L74)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

I don't like how the derived classes' `UpdateYdotAndError` are forced to use `v_proj`. 
Maybe we can add a boolean member `impact_invariant_projection_` (with a public setter) to `OscTrackingData`, and in line 74 here we add 
```
if (impact_invariant_projection_)
  error_ydot_ -= GetJ() * v_proj;
` ``
</blockquote></details>

great suggestion, thanks!
___
*[examples/Cassie/osc_jump/basic_trajectory_passthrough.cc, line 10 at r1](https://reviewable.io/reviews/dairlab/dairlib/232#-MVznK6c1HPX9D00nzb2:-MXhGE-s0ZOMVQIZnQxR:b-yx3gnq) ([raw file](https://github.com/dairlab/dairlib/blob/3b984c1a190eff3b555f305b8a14e2b07edf11f8/examples/Cassie/osc_jump/basic_trajectory_passthrough.cc#L10)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Looks like this class can be replaced by Drake's `ConstantValueSource`?
</blockquote></details>

I wasn't able to make that, i couldn't find any good examples of using `ConstantValueSource` with a piecewise polynomial


<!-- Sent from Reviewable.io -->

2021-07-26 01:43 UTC, yminchen approved these changes
All comments were addressed. Feel free to merge once the conflicts are resolved

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/232#-:-MfVTPdC2FhWkyLSJrdh:bk8ap70)* status: all files reviewed, 10 unresolved discussions (waiting on @yminchen)



<!-- Sent from Reviewable.io -->

2021-08-02 20:52 UTC, merged