Modeling encoders and actuator delay in cassie sim
DAIRLab/dairlib pull request #248
Opened 2021-07-20 14:37 UTC by yangwill

This PR adds in actuator delay and encoder resolution to the Cassie sim
- Actuator delay can be set to 0 to remove its effect
- The encoder resolution is only applied to the `lcmt_cassie_out` message similar to Mujoco, this way the `lcmt_robot_output` remains as the ground truth robot state.

2021-07-20 19:19 UTC, Brian-Acosta commented on systems/primitives/encoder.h
> +static int drive_filter_b[DRIVE_FILTER_NB] = {2727, 534, -2658, -795, 72,
We should not be defining Cassie-specific values in a general purpose system like this

2021-07-20 19:25 UTC, Brian-Acosta commented on examples/Cassie/cassie_utils.cc
> +  std::vector<int> joint_selections = {7,  8,  9,  10, 11, 12, 13,
Should use drake indexing functions instead of hand coded numbers

2021-07-20 19:26 UTC, Brian-Acosta commented on examples/Cassie/cassie_utils.cc
> +  std::vector<int> ticks_per_revolution = {
Also need to use drake indexing functions here so make sure the joints and the resolutions are in the same order

2021-07-20 19:27 UTC, Brian-Acosta requested changes
See comments - Looks good otherwise

2021-07-21 12:44 UTC, yminchen requested changes
> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/248)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[examples/Cassie/cassie_utils.cc, line 201 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf3LKM3DwoqpwllUbXW-r1-201:-Mf7zwS81gEiNbcthCab:b-qezo8i) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/examples/Cassie/cassie_utils.cc#L201)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Should use drake indexing functions instead of hand coded numbers 
</blockquote></details>

I second this
___
*[examples/Cassie/multibody_sim.cc, line 110 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf7ypXs4NG4roAwocgb:-Mf7ypXs4NG4roAwocgc:bhok0lb) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/examples/Cassie/multibody_sim.cc#L110)):*
> ```cpp
>   auto discrete_time_delay =
>       builder.AddSystem<drake::systems::DiscreteTimeDelay>(
>           1.0 / FLAGS_publish_rate, FLAGS_actuator_delay,
> ```

The second argument seems wrong. It should be the number of updates we want to delay the signal by. 
https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_discrete_time_delay.html#a50bf5113d6d51906af0d3038bee47f92

So in this case, it would be `builder.AddSystem<drake::systems::DiscreteTimeDelay>(
          1.0 / FLAGS_publish_rate, FLAGS_actuator_delay * FLAGS_publish_rate, plant.num_actuators());`
___
*[systems/primitives/encoder.h, line 18 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf81m5o7SyJDtzK2UQ1:-Mf81m5o7SyJDtzK2UQ2:b-tu7zbu) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/systems/primitives/encoder.h#L18)):*
> ```
> #define DRIVE_FILTER_NB 9
> #define JOINT_FILTER_NB 4
> #define JOINT_FILTER_NA 3
> ```
What are these three numbers? Also, we should probably delete `DRIVE_FILTER_NB` and the struct `DriveFilter` because they are not used in `Encoder` class. 
___
*[systems/primitives/encoder.h, line 30 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf833q-4KurRKNiChRG:-Mf833q-4KurRKNiChRH:b-wx31lw) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/systems/primitives/encoder.h#L30)):*
> ```objc
> /// this class is copied from drake/systems/primitives/Passthrough
> /// with the modification that it adds random noise to the values it is
> /// passing through
> ```

This class doesn't seem to add random noise. Also, could you describe the algorithm in detail here? What kind of filter is used here? 


<!-- Sent from Reviewable.io -->

2021-07-21 12:47 UTC, yminchen reviewed
Thanks for adding this. Please see the comments

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/248#-:-Mf85c5h8_zqBkjILZWB:bs6uyxs)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @Brian-Acosta and @yangwill)



<!-- Sent from Reviewable.io -->

2021-07-21 17:47 UTC, yangwill reviewed
Renamed the encoder class to be Cassie-specific and used indexing functions to work different models of cassie (fixed-base, without springs).

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/248#-:-Mf9AJdl221a-zLcGd5O:b7vs17r)* status: 1 of 9 files reviewed, 6 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[examples/Cassie/cassie_utils.cc, line 201 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf3LKM3DwoqpwllUbXW-r1-201:-Mf9AHxl7K4Grg34xrZM:bb7f2mf) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/examples/Cassie/cassie_utils.cc#L201)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

I second this
</blockquote></details>

done
___
*[examples/Cassie/cassie_utils.cc, line 204 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf3LKM3DwoqpwllUbXW-r1-204:-Mf9AIgc-AyciOJNFHom:bb7f2mf) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/examples/Cassie/cassie_utils.cc#L204)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Also need to use drake indexing functions here so make sure the joints and the resolutions are in the same order
</blockquote></details>

done
___
*[examples/Cassie/multibody_sim.cc, line 110 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf7ypXs4NG4roAwocgb:-Mf8K5vd3Q8hZ8pwDINB:bhd9gur) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/examples/Cassie/multibody_sim.cc#L110)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

The second argument seems wrong. It should be the number of updates we want to delay the signal by. 
https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_discrete_time_delay.html#a50bf5113d6d51906af0d3038bee47f92

So in this case, it would be `builder.AddSystem<drake::systems::DiscreteTimeDelay>(
          1.0 / FLAGS_publish_rate, FLAGS_actuator_delay * FLAGS_publish_rate, plant.num_actuators());`
</blockquote></details>

Oh good catch, though I think it should be `FLAGS_actuator_delay / FLAGS_publish_rate`
___
*[systems/primitives/encoder.h, line 18 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf81m5o7SyJDtzK2UQ1:-Mf8LRtFCthOgjWA4Tr6:b-vfqcio) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/systems/primitives/encoder.h#L18)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> ```
> #define DRIVE_FILTER_NB 9
> #define JOINT_FILTER_NB 4
> #define JOINT_FILTER_NA 3
> ```
What are these three numbers? Also, we should probably delete `DRIVE_FILTER_NB` and the struct `DriveFilter` because they are not used in `Encoder` class. 
</blockquote></details>

These were taken from the Mujoco sim, they correspond to the buffer size for the velocity filter.
___
*[systems/primitives/encoder.h, line 20 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf3LKM3DwoqpwllUbXa-r1-20:-Mf9A9qy4on1Myf5cEpW:bnwyksl) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/systems/primitives/encoder.h#L20)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

We should not be defining Cassie-specific values in a general purpose system like this
</blockquote></details>

Good point, renamed the class to be cassie specific.
___
*[systems/primitives/encoder.h, line 30 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf833q-4KurRKNiChRG:-Mf8dQtrAO0t6feeBFa0:bhoo7se) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/systems/primitives/encoder.h#L30)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

This class doesn't seem to add random noise. Also, could you describe the algorithm in detail here? What kind of filter is used here? 
</blockquote></details>

Fixed the description


<!-- Sent from Reviewable.io -->

2021-07-21 18:15 UTC, yminchen requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/248)* status: all files reviewed, 6 unresolved discussions (waiting on @Brian-Acosta, @yangwill, and @yminchen)

___
*[examples/Cassie/multibody_sim.cc, line 110 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf7ypXs4NG4roAwocgb:-Mf9GY0X8xTM3Ld9yUqB:b-288lac) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/examples/Cassie/multibody_sim.cc#L110)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Oh good catch, though I think it should be `FLAGS_actuator_delay / FLAGS_publish_rate`
</blockquote></details>

Hmmm, isn't `FLAGS_actuator_delay` in seconds and `FLAGS_publish_rate` in `1/s`? 


<!-- Sent from Reviewable.io -->

2021-07-21 18:23 UTC, yangwill reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/248)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[examples/Cassie/multibody_sim.cc, line 110 at r1](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf7ypXs4NG4roAwocgb:-Mf9IfZk50c_oVge6mU4:b-utetdi) ([raw file](https://github.com/dairlab/dairlib/blob/14fdeba1ae7e5c8e2b2be3b22eba86962ab039c8/examples/Cassie/multibody_sim.cc#L110)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Hmmm, isn't `FLAGS_actuator_delay` in seconds and `FLAGS_publish_rate` in `1/s`? 
</blockquote></details>

Oops, yes you're right, fixed it!


<!-- Sent from Reviewable.io -->

2021-07-21 18:31 UTC, Brian-Acosta commented on examples/Cassie/cassie_encoder.h
> +#define ENC_RES_LOW 8192
A bit of a nitpick but I would like to see these named CASSIE_ENC_RES_LOW and _HIGH to avoid future naming conflicts

2021-07-21 18:31 UTC, Brian-Acosta commented on examples/Cassie/cassie_encoder.h
> +#define JOINT_FILTER_NB 4
could also use a CASSIE prefix here

2021-07-21 18:32 UTC, Brian-Acosta approved these changes
LGTM pending two minor comments

2021-07-21 18:50 UTC, yangwill reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/248)* status: 8 of 9 files reviewed, 8 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[examples/Cassie/cassie_encoder.h, line 15 at r2](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf9A75erKvCKt0E7T_t-r2-15:-Mf9Op5N1y5_BVn4n9Pc:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/4dbbd9495e25408b5d6be35f8912ee2d285a14b8/examples/Cassie/cassie_encoder.h#L15)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

A bit of a nitpick but I would like to see these named CASSIE_ENC_RES_LOW and _HIGH to avoid future naming conflicts
</blockquote></details>

Done.
___
*[examples/Cassie/cassie_encoder.h, line 18 at r2](https://reviewable.io/reviews/dairlab/dairlib/248#-Mf9A75erKvCKt0E7T_t-r2-18:-Mf9OpOz0UYH8NhtXHaT:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/4dbbd9495e25408b5d6be35f8912ee2d285a14b8/examples/Cassie/cassie_encoder.h#L18)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

could also use a CASSIE prefix here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-21 18:57 UTC, yminchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/248#-:-Mf9QUQp6-JzRiYaKBHS:bnfp4nl)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @Brian-Acosta and @yminchen)



<!-- Sent from Reviewable.io -->

2021-07-21 19:08 UTC, merged