Icra demo
DAIRLab/dairlib pull request #299
Opened 2022-05-27 21:23 UTC by Brian-Acosta

Merging in quality of life updates made for ICRA demo

2022-05-30 21:09 UTC, yangwill requested changes
> Reviewed 1 of 2 files at r2, 5 of 26 files at r3, 7 of 33 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: 13 of 60 files reviewed, 3 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[`bindings/pydairlib/analysis/mbp_plotting_utils.py` line 11 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3LkvzxAGrI0shVbpsb:-N3LkvzxAGrI0shVbpsc:bwz1kqp) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/bindings/pydairlib/analysis/mbp_plotting_utils.py#L11)):*
> ```Python
> 
> ps = plot_styler.PlotStyler()
> ps.set_default_styling()
> ```

Probably should make a separate PR for all the cassie log plotter features.

I know I have a few changes to the plotter on my branch as well.
___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 132 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3LmwSC3-H3mDNFsCoJ:-N3LmwSC3-H3mDNFsCoK:b-868zay) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/run_osc_walking_controller_alip.cc#L132)):*
> ```cpp
> 
>   // Get body frames and points
>   Vector3d mid_contact_point = left_heel.first +
> ```

rename mid_contact_point to maybe something like desired_center_of_pressure? Unless that's not what this variable refers to.
___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 294 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Ln6kACIS4xPYFdhzP:-N3Ln6kACIS4xPYFdhzQ:buc8ojc) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/run_osc_walking_controller_alip.cc#L294)):*
> ```cpp
>     contact_points_in_each_state.push_back({right_toe_mid});
>   }
>   auto alip_traj_generator = builder.AddSystem<systems::ALIPTrajGenerator>(
> ```

Let's have separate files for the kalman filter gains.


<!-- Sent from Reviewable.io -->

2022-05-30 22:49 UTC, Brian-Acosta reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: 8 of 60 files reviewed, 3 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 132 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3LmwSC3-H3mDNFsCoJ:-N3M8mt9Cw6rYxIFx8cn:bb7f2mf) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/run_osc_walking_controller_alip.cc#L132)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

rename mid_contact_point to maybe something like desired_center_of_pressure? Unless that's not what this variable refers to.
</blockquote></details>

done
___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 294 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Ln6kACIS4xPYFdhzP:-N3M8pCP9BFhHzygoQX6:bqda7lm) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/run_osc_walking_controller_alip.cc#L294)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Let's have separate files for the kalman filter gains.
</blockquote></details>

any reason why?
___
*[`bindings/pydairlib/analysis/mbp_plotting_utils.py` line 11 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3LkvzxAGrI0shVbpsb:-N3M8xfq2Mi7tGSwYBJ8:bvawltz) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/bindings/pydairlib/analysis/mbp_plotting_utils.py#L11)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Probably should make a separate PR for all the cassie log plotter features.

I know I have a few changes to the plotter on my branch as well.
</blockquote></details>

Reverted for now


<!-- Sent from Reviewable.io -->

2022-05-30 23:55 UTC, yangwill requested changes
> Reviewed 2 of 10 files at r1, 1 of 26 files at r3, 1 of 2 files at r5, 9 of 33 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: 21 of 60 files reviewed, 7 unresolved discussions (waiting on @Brian-Acosta, @yangwill, and @yminchen)

___
*[`examples/Cassie/director_scripts/cassie_operator.py` line 3 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MBlhe931nHaCAgq-J:-N3MBlhe931nHaCAgq-K:b-ec5c38) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/director_scripts/cassie_operator.py#L3)):*
> ```Python
> import sys
> import time
> import math
> ```

Should clean up this file, or because we're migrating to meshcat anyway, we should make the equivalent thing in meshcat
___
*[`examples/Cassie/networking/udp_lcm_translator.h` line 21 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MC4Vg47ah3PPJ_I0N:-N3MC4Vg47ah3PPJ_I0O:ba0746i) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/networking/udp_lcm_translator.h#L21)):*
> ```objc
>     lcmt_cassie_in* message);
> 
> void cassieOutToLcm(const cassie_out_t& cassie_out, double time_seconds,
> ```

If we're renaming the variables, we should enforce naming conventions so CassieOutToLcm and CassieInToLcm
___
*[`examples/Cassie/osc/high_level_command.cc` line 123 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MNcL-3r5KM2plnEuF:-N3MNcL-3r5KM2plnEuG:b-a4dfmk) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/osc/high_level_command.cc#L123)):*
> ```cpp
>     //                  2: lateral_vel (left joystick left/right)
> 
>     double vel_scale_trans_sagital =
> ```

we should (maybe in a future PR) add a discrete time filter function to replace everywhere we do this.
___
*[`examples/Cassie/osc/hip_yaw_traj_gen.cc` line 35 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MNw-M3UYeXSfRSOS_:-N3MNw-M3UYeXSfRSOSa:bimv54t) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/osc/hip_yaw_traj_gen.cc#L35)):*
> ```cpp
>   int fsm = this->EvalVectorInput(context, fsm_port_)->value()(0);
> 
>   yaw(0) = (fsm == left_stance_state_) ?
> ```

why is left explicit here? 


<!-- Sent from Reviewable.io -->

2022-05-31 02:18 UTC, yminchen requested changes
> Reviewed 1 of 10 files at r1, 1 of 2 files at r2, 13 of 26 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, 17 of 33 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: all files reviewed, 16 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 570 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MqCTg1XgD89DolboE:-N3MqCTg1XgD89DolboF:b7i2wit) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/run_osc_walking_controller_alip.cc#L570)):*
> ```cpp
>   osc->SetOsqpSolverOptionsFromYaml(
>       "examples/Cassie/osc/solver_settings/osqp_options_walking.yaml");
>   // Build OSC problem
> ```

This commend is for `osc->Build();`
___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 575 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MpaSn4bCohrCk0twJ:-N3MpaSn4bCohrCk0twK:b-nj2acg) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/run_osc_walking_controller_alip.cc#L575)):*
> ```cpp
>   osc->AddInputCostByJointAndFsmState("toe_left_motor", post_right_double_support_state, 1.0);
>   osc->AddInputCostByJointAndFsmState("toe_right_motor", right_stance_state, 1.0);
>   osc->AddInputCostByJointAndFsmState("toe_right_motor", post_left_double_support_state, 1.0);
> ```

We should check that the cost weight for COM tracking in x is 0 when we penalize toe motor effort 
___
*[`examples/Cassie/start_logging.py` line 9 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MqbW54bunYenRqxsS:-N3MqbW54bunYenRqxsT:b-ciw87i) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/start_logging.py#L9)):*
> ```Python
> 
> def main():
>     sim = (os.getlogin() == 'brian')
> ```

Make this general to all users. Something like sim = not (username == cassie and hostname == cassie)
___
*[`examples/Cassie/director_scripts/cassie_operator.py` line 118 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MrN4m-rTNAApEq_5q:-N3MrN4m-rTNAApEq_5r:bkxjoe5) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/director_scripts/cassie_operator.py#L118)):*
> ```Python
>         #     self.ledits[idx + 2*len(joint_names)].setMinimum(-100)
>         #     self.ledits[idx + 2*len(joint_names)].setMaximum(100)
>         #     self.ledits[idx + 2*len(joint_names)].setSingleStep(1)
> ```

Remove the dead code 



_Code quote:_
```Python
        # grid.addWidget(QLabel("Desired Position"), 0, 1)
        # grid.addWidget(QLabel("KP"), 0, 3)
        # grid.addWidget(QLabel("KD"), 0, 5)

        # for idx, name in enumerate(joint_names):
        #     grid.addWidget(labels[idx], idx+1, 0)
        #     grid.addWidget(self.ledits[idx], idx+1, 1)
        #     self.ledits[idx].setMinimum(-3.14)
        #     self.ledits[idx].setMaximum(3.14)
        #     self.ledits[idx].setSingleStep(.01)
        #
        #     grid.addWidget(self.ledits[idx + len(joint_names)], idx+1, 3)
        #
        #     self.ledits[idx + len(joint_names)].setMinimum(-100)
        #     self.ledits[idx + len(joint_names)].setMaximum(100)
        #     self.ledits[idx + len(joint_names)].setSingleStep(1)
        #
        #     grid.addWidget(self.ledits[idx + 2*len(joint_names)], idx+1, 5)
        #     self.ledits[idx + 2*len(joint_names)].setMinimum(-100)
        #     self.ledits[idx + 2*len(joint_names)].setMaximum(100)
        #     self.ledits[idx + 2*len(joint_names)].setSingleStep(1)
```
___
*[`examples/Cassie/systems/cassie_out_to_radio.h` line 11 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Ms2DLCaKSygkx9uTA:-N3Ms2DLCaKSygkx9uTB:b5xtusy) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/systems/cassie_out_to_radio.h#L11)):*
> ```objc
> namespace systems {
> 
> class CassieOutToRadio : public drake::systems::LeafSystem<double> {
> ```

It would be great to have a short description for what this class is doing in the beginning here.n
___
*[`examples/Cassie/systems/cassie_out_to_radio.h` line 29 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Mrx3r-d_inm63V7fQ:-N3Mrx3r-d_inm63V7fR:b6h7mzg) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/systems/cassie_out_to_radio.h#L29)):*
> ```objc
> 
>  private:
>   bool is_abstract() const { return false; }
> ```

What is this is_abstract() function?
___
*[`systems/filters/linear_kalman_filter.h` line 39 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Mtu589VeYZwguf7Ha:-N3Mtu589VeYZwguf7Hb:bdjqf5f) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/systems/filters/linear_kalman_filter.h#L39)):*
> ```objc
>   Eigen::MatrixXd P_;
>   Eigen::VectorXd x_;
>   double rate_ = .001;
> ```

Should this parameter be specified in the constructor?
___
*[`systems/filters/linear_kalman_filter.cc` line 30 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Mty4t6hADRJTln27g:-N3Mty4t6hADRJTln27h:bdjqf5f) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/systems/filters/linear_kalman_filter.cc#L30)):*
> ```cpp
>   double dt  = t - t_;
> 
>   if (dt > 100* rate_) {
> ```

Should this parameter be specified in the constructor?
___
*[`examples/Cassie/systems/input_supervisor.h` line 9 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MsSz22L7gSRuFKt0M:-N3MsSz22L7gSRuFKt0N:b2aj545) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/systems/input_supervisor.h#L9)):*
> ```objc
> 
> #include "external/drake/tools/install/libdrake/_virtual_includes/drake_shared_library/drake/multibody/plant/multibody_plant.h"
> #include "external/drake/tools/install/libdrake/_virtual_includes/drake_shared_library/drake/systems/framework/leaf_system.h"
> ```

This is the first time I see #include "external/drake/...". Why can't we just use `#include "drake/multibody/plant/multibody_plant.h"`?


<!-- Sent from Reviewable.io -->

2022-05-31 14:29 UTC, yangwill requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: all files reviewed, 14 unresolved discussions (waiting on @Brian-Acosta)

___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 294 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Ln6kACIS4xPYFdhzP:-N3PW5wf3s-EjWEQve2S:b-5kf6m3) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/run_osc_walking_controller_alip.cc#L294)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

any reason why?
</blockquote></details>

To make it easier to mix and match gain files. If we change our state estimator, we might want different gains for the ALIP kalman filter but that shouldn't affect our walking controller gains.


<!-- Sent from Reviewable.io -->

2022-05-31 14:38 UTC, yangwill requested changes
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: all files reviewed, 17 unresolved discussions (waiting on @Brian-Acosta)

___
*[`systems/controllers/osc/operational_space_control.h` line 331 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3PXXhV8QDAFGUsmFMR:-N3PXXhV8QDAFGUsmFMS:b-ha83ox) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/systems/controllers/osc/operational_space_control.h#L331)):*
> ```objc
>   Eigen::MatrixXd W_input_;        // Input cost weight
>   Eigen::MatrixXd W_joint_accel_;  // Joint acceleration cost weight
>   std::map<int, std::pair<int, double>> fsm_to_w_input_map_; // each pair is (joint index, weight)
> ```

Maybe we should instead have every regularization weight be indexed by fsm, or have the option for that.
___
*[`systems/controllers/osc/operational_space_control.cc` line 731 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3PXi-kD38p57oP8zYu:-N3PXi-kD38p57oP8zYv:b2jk9m) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/systems/controllers/osc/operational_space_control.cc#L731)):*
> ```cpp
> 
> 
>   // test joint-level input cost by fsm state
> ```

I don't think this actually changes the cost in different fsm states, because this is only called once and not per control loop.
___
*[`examples/Cassie/systems/sim_cassie_sensor_aggregator.h` line 17 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3PWvwv9mOCL2NwznRQ:-N3PWvwv9mOCL2NwznRR:b-xobmfr) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/systems/sim_cassie_sensor_aggregator.h#L17)):*
> ```objc
> #include "systems/framework/timestamped_vector.h"
> 
> #include "external/drake/tools/install/libdrake/_virtual_includes/drake_shared_library/drake/multibody/plant/multibody_plant.h"
> ```

fix includes here too


<!-- Sent from Reviewable.io -->

2022-05-31 14:52 UTC, yminchen requested changes
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: all files reviewed, 17 unresolved discussions (waiting on @Brian-Acosta)

___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 570 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MqCTg1XgD89DolboE:-N3PaU2092BUGVtdiDBv:b-g30g7a) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/run_osc_walking_controller_alip.cc#L570)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

This commend is for `osc->Build();`
</blockquote></details>

*comment
___
*[`examples/Cassie/systems/cassie_out_to_radio.h` line 29 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Mrx3r-d_inm63V7fQ:-N3P_DswDO9M8kWOO53N:b-4asr0y) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/systems/cassie_out_to_radio.h#L29)):*
> What is this is_abstract() function?
Sorry I found my previous question too vague and kinda weird lol. 
I think this is a dead method that should be removed because it's not used anywhere?


<!-- Sent from Reviewable.io -->

2022-05-31 19:21 UTC, Brian-Acosta reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: all files reviewed, 17 unresolved discussions (waiting on @yangwill and @yminchen)

___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 294 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Ln6kACIS4xPYFdhzP:-N3QEYp22TM8Ez7PwXb1:b-db7nq6) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/run_osc_walking_controller_alip.cc#L294)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

To make it easier to mix and match gain files. If we change our state estimator, we might want different gains for the ALIP kalman filter but that shouldn't affect our walking controller gains.
</blockquote></details>

My thought was that since the alip kalman filter is part of the alip walking controller diagram, the gains should be in the same place as the rest of the gains for that diagram
___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 570 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MqCTg1XgD89DolboE:-N3QEzakCH0OlIFKSdLe:bomrr8p) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/run_osc_walking_controller_alip.cc#L570)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

*comment
</blockquote></details>

Removed the comment since it's pretty self evident what osc->Build() does 
___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 575 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MpaSn4bCohrCk0twJ:-N3QG-36BIjuKhpx9HLd:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/run_osc_walking_controller_alip.cc#L575)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

We should check that the cost weight for COM tracking in x is 0 when we penalize toe motor effort 
</blockquote></details>

Done
___
*[`examples/Cassie/start_logging.py` line 9 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MqbW54bunYenRqxsS:-N3QGHUAARno9acj7zPP:binvst2) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/start_logging.py#L9)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Make this general to all users. Something like sim = not (username == cassie and hostname == cassie)
</blockquote></details>

Removing this file for now since the version on Cassie has the correct changes applied
___
*[`examples/Cassie/director_scripts/cassie_operator.py` line 3 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MBlhe931nHaCAgq-J:-N3QHwX12cvInkUYZkXM:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/director_scripts/cassie_operator.py#L3)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Should clean up this file, or because we're migrating to meshcat anyway, we should make the equivalent thing in meshcat
</blockquote></details>

Done
___
*[`examples/Cassie/director_scripts/cassie_operator.py` line 118 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MrN4m-rTNAApEq_5q:-N3QHxZF6Cqx3vY9pvPf:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/director_scripts/cassie_operator.py#L118)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

Remove the dead code 
</blockquote></details>

Done
___
*[`examples/Cassie/networking/udp_lcm_translator.h` line 21 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MC4Vg47ah3PPJ_I0N:-N3QYftyBiJ21SQhUOhL:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/networking/udp_lcm_translator.h#L21)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

If we're renaming the variables, we should enforce naming conventions so CassieOutToLcm and CassieInToLcm
</blockquote></details>

Done
___
*[`examples/Cassie/osc/high_level_command.cc` line 123 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MNcL-3r5KM2plnEuF:-N3QM1B5778jnbKMBs_U:bsaozf4) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/osc/high_level_command.cc#L123)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

we should (maybe in a future PR) add a discrete time filter function to replace everywhere we do this.
</blockquote></details>

Yeah I agree. Probably for a future PR though
___
*[`examples/Cassie/osc/hip_yaw_traj_gen.cc` line 35 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MNw-M3UYeXSfRSOS_:-N3QYimSCosqiuCc4PMW:b-jimqqc) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/osc/hip_yaw_traj_gen.cc#L35)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

why is left explicit here? 
</blockquote></details>

No particular reason other than it's easier than specifying both left and right. We could rename the variable to allow for left or right without changing the functionality of the system if you want.
___
*[`examples/Cassie/systems/cassie_out_to_radio.h` line 11 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Ms2DLCaKSygkx9uTA:-N3QNU4G23V_Jcx6GJ8h:bb6un1j) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/systems/cassie_out_to_radio.h#L11)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

It would be great to have a short description for what this class is doing in the beginning here.n
</blockquote></details>

Done
___
*[`examples/Cassie/systems/cassie_out_to_radio.h` line 29 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Mrx3r-d_inm63V7fQ:-N3QMStfCZY_q888yTR4:bmy13by) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/examples/Cassie/systems/cassie_out_to_radio.h#L29)):*
<details><summary><i>Previously, yminchen (Yu-Ming Chen) wrote…</i></summary><blockquote>

> What is this is_abstract() function?
Sorry I found my previous question too vague and kinda weird lol. 
I think this is a dead method that should be removed because it's not used anywhere?
</blockquote></details>

I just copied Will's implementation, maybe he needed it. Anyway I removed it
___
*[`systems/controllers/osc/operational_space_control.h` line 331 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3PXXhV8QDAFGUsmFMR:-N3QP5yM4C4T51BaaHKP:b82ijb7) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/systems/controllers/osc/operational_space_control.h#L331)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Maybe we should instead have every regularization weight be indexed by fsm, or have the option for that.
</blockquote></details>

Yeah that could be useful
___
*[`systems/controllers/osc/operational_space_control.cc` line 731 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3PXi-kD38p57oP8zYu:-N3QP_Ce6KRSdhmR-7fl:b-hw5bkn) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/systems/controllers/osc/operational_space_control.cc#L731)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

I don't think this actually changes the cost in different fsm states, because this is only called once and not per control loop.
</blockquote></details>

Not sure what you mean. This is in SolveQp() which is called every control loop
___
*[`systems/filters/linear_kalman_filter.h` line 39 at r8]( [...]

2022-05-31 20:01 UTC, yangwill requested changes
> Reviewed 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: all files reviewed, 11 unresolved discussions (waiting on @Brian-Acosta and @yminchen)

___
*[`examples/Cassie/run_osc_walking_controller_alip.cc` line 294 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3Ln6kACIS4xPYFdhzP:-N3Qgc0XD9w3Z1qrHuVB:b-tfti7) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/run_osc_walking_controller_alip.cc#L294)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

My thought was that since the alip kalman filter is part of the alip walking controller diagram, the gains should be in the same place as the rest of the gains for that diagram
</blockquote></details>

Ok let's leave it here for now, but i think it makes sense to pull out the kalman filter and construct it outside of this constructor.
___
*[`examples/Cassie/osc/hip_yaw_traj_gen.cc` line 35 at r6](https://reviewable.io/reviews/dairlab/dairlib/299#-N3MNw-M3UYeXSfRSOS_:-N3Qgve48xNzZwlCQaiT:b-z5h34t) ([raw file](https://github.com/dairlab/dairlib/blob/9ac930c0a4c8c217ee74b2fa6e6bfb036dfedc93/examples/Cassie/osc/hip_yaw_traj_gen.cc#L35)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

No particular reason other than it's easier than specifying both left and right. We could rename the variable to allow for left or right without changing the functionality of the system if you want.
</blockquote></details>

Just not sure why the output port is also named `hip_yaw_left`. maybe just update the output port name leave everything else as is. Also could be cleaner to define a variable that is -1 for left stance and 1 for right stance and then multiply that by 0.5 * radio.channel[7]. That way it's clear that all the left stance check is doing is flipping the angle.
___
*[`systems/controllers/osc/operational_space_control.cc` line 731 at r8](https://reviewable.io/reviews/dairlab/dairlib/299#-N3PXi-kD38p57oP8zYu:-N3QgHVb631k2JYGNDst:bwhqymm) ([raw file](https://github.com/dairlab/dairlib/blob/134aa1c0cabdab5f82e05121462fcd7151bc9050/systems/controllers/osc/operational_space_control.cc#L731)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Not sure what you mean. This is in SolveQp() which is called every control loop
</blockquote></details>

oh my bad, reviewable collapsed a bunch of lines. Looks good, though we should update OSC to save the fsm dependent weights in a future PR to avoid unnecessarily constructing matrices


<!-- Sent from Reviewable.io -->

2022-06-01 01:07 UTC, yminchen reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: all files reviewed, 2 unresolved discussions (waiting on @Brian-Acosta)



<!-- Sent from Reviewable.io -->

2022-06-01 15:02 UTC, yangwill approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Brian-Acosta)



<!-- Sent from Reviewable.io -->

2022-06-01 20:57 UTC, Brian-Acosta reviewed
@yminchen can you re-review when you get the chance? I'd like to merge so I can update my branch

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299#-:-N3W2TJnAR3cntS6NW2W:bu8bsk4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Brian-Acosta)



<!-- Sent from Reviewable.io -->

2022-06-07 01:18 UTC, yminchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/299#-:-N3vjVAT1vy9gMqGml3R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Brian-Acosta)



<!-- Sent from Reviewable.io -->

2022-06-07 01:46 UTC, merged