Add residual analysis tools
DAIRLab/dairlib pull request #313
Opened 2022-08-12 17:19 UTC by HaoxiangYou

Add residual analysis tools for cassie

2022-08-15 18:35 UTC, yangwill requested changes
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313)* status: all files reviewed, 35 unresolved discussions (waiting on @Brian-Acosta and @HaoxiangYou)

___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 51 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xclmh50NueXd5o9P1:-N9Xclmh50NueXd5o9P2:bmi48u8) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L51)):*
> ```Python
> 
>     def initial_spring_and_damping(self):
>         self.K = np.zeros((22,23))
> ```

Try to avoid hardcoding the size of the robot position/velocity vectors. Drake has a method that gets the number of positions/velocities `self.plant.num_positions()` and `self.plant.num_velocities()`
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 66 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XdODp5m78KTZapgW8:-N9XdODp5m78KTZapgW9:b-hagu4v) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L66)):*
> ```Python
>                 self.C[self.vel_map[joint.name() + 'dot'], self.vel_map[joint.name() + 'dot']] = joint.damping()
>     
>     def drawPose(self, q):
> ```

method names should use the same naming convention, so to be like the other methods it should be `draw_pose(self, q)`
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 69 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XdcLs3G7biLiOC5sy:-N9XdcLtEwyYCic6Z3wM:b-q3w2p9) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L69)):*
> ```Python
>         self.visualizer.DrawPoses(q)
> 
>     def get_spring_stiffness(self, K):
> ```

Small comment, but conventionally methods with the word `get` in them are for returning member variables. If the method is setting member variables, it usually has `set` in its name. So this should be `set_spring_stiffness`
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 72 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XdvMB4QDPry7SnYXg:-N9XdvMB4QDPry7SnYXh:b-52gn1z) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L72)):*
> ```Python
>         self.K = K
>     
>     def get_damping(self, C):
> ```

this method should be `set_damping`
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 75 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xdy1L7dVnbWqbXSfB:-N9Xdy1L7dVnbWqbXSfC:bwq5v63) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L75)):*
> ```Python
>         self.C = C
> 
>     def get_spring_offset(self, offset):
> ```

also here, it should be `set_spring_offset`
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 84 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xe5WD3sKR2ygjdRxX:-N9Xe5WD3sKR2ygjdRxY:bwhrcl7) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L84)):*
> ```Python
>         new_v = v + dt * v
>         new_q[4:] = q[4:] + dt * v[3:]
>         new_q[:4] = ((Rotation.from_quat(q[[1,2,3,0]]) * Rotation.from_rotvec(dt * v[:3])).as_quat())[[3,0,1,2]]
> ```

what does this function do? It looks like integration but not quite. If a function's purpose isn't obvious, add a comment explaining the function.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 129 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xeo1S3urrGzn0nKiC:-N9Xeo1S3urrGzn0nKiD:bonp5pa) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L129)):*
> ```Python
>             if np.array_equal(is_contact, np.array([1,0])):
>                 self.K[self.vel_map["knee_joint_leftdot"],self.pos_map["knee_joint_left"]] = 1749.1496
>                 self.K[self.vel_map["ankle_spring_joint_leftdot"],self.pos_map["ankle_spring_joint_left"]] = 1026.3388
> ```

Where are these values from?
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 165 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XesNtE5WUq1WV0pbl:-N9XesNtE5WUq1WV0pbm:bln0nu) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L165)):*
> ```Python
> 
>         # Get the J_h term
>         J_h = np.zeros((2, 22))
> ```

again, avoid hardcoding matrix shapes if possible.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 254 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XfFb06zTu7xM1MDxS:-N9XfFb06zTu7xM1MDxT:bbe0at5) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L254)):*
> ```Python
>         }
> 
>         self.intermediate_variables.append(intermediate_variables)
> ```

small comment, try to not name the list of intermediate variables the same name as each individual element in the list.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 280 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XfY175_SLQIUVFXwG:-N9XfY175_SLQIUVFXwH:bg1w8ld) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L280)):*
> ```Python
>         return left_toe_mid_point_on_world, right_toe_mid_point_on_world, v_left_toe_mid_in_world, v_right_toe_mid_in_world
> 
>     def get_J_c_ative_and_J_c_active_dot_v(self, is_contact, lambda_c_gt, lambda_c_position):
> ```

This does seems like not the most efficient way to write this function.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 343 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xfll39wXENKJRpfv9:-N9Xfll39wXENKJRpfvA:bwudvxs) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L343)):*
> ```Python
>                 num_contact_unknown += 3
> 
>             get_force_at_point_matrix = np.zeros((12, num_contact_unknown))
> ```

the function of this matrix is not clear without comments
___
*[`bindings/pydairlib/analysis/residual_analysis/data_processor.py` line 7 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xi-2q1zM7uJRwzYwh:-N9Xi-2q1zM7uJRwzYwi:b-5xynpx) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/data_processor.py#L7)):*
> ```Python
> from utils import *
> from scipy.spatial.transform import Rotation
> class DataProcessor():
> ```

Name should be more specific. this is not a general data processor.
___
*[`bindings/pydairlib/analysis/residual_analysis/data_processor.py` line 12 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xhqz72x_bIkb-V_7S:-N9Xhqz8Ef5Dp6hjAFIu:bi01fb6) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/data_processor.py#L12)):*
> ```Python
>         pass
> 
>     def update_pos_map(self, pos_map, pos_map_inverse):
> ```

same comment about get/set. This should be called `set_pos_map`. Though I'm not sure why the pos_map should ever be updated.
___
*[`bindings/pydairlib/analysis/residual_analysis/data_processor.py` line 73 at r1](https://re [...]

2022-08-30 19:21 UTC, yangwill requested changes
> Reviewed 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313)* status: all files reviewed, 21 unresolved discussions (waiting on @Brian-Acosta and @HaoxiangYou)

___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 129 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xeo1S3urrGzn0nKiC:-NAk85Rm8CQkWLjeMFam:b1i4517) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L129)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Where are these values from?
</blockquote></details>

Are these values consistent between logs? Do they need to be hardcoded? If so, can we store the hardcoded values in a separate file along with the log that was used to generate the values?
___
*[`bindings/pydairlib/analysis/residual_analysis/plot_utlis.py` line 79 at r3](https://reviewable.io/reviews/dairlab/dairlib/313#-NAkAsKMAB8A_oMLQr2i:-NAkAsKN6LfvQNqwMyQW:b-s0m4j1) ([raw file](https://github.com/dairlab/dairlib/blob/bf2b67f7cd342a250a54b9f235efc043d797fef9/bindings/pydairlib/analysis/residual_analysis/plot_utlis.py#L79)):*
> ```Python
>     plot_given_keys_vs_time(cut_data, x, ys, joint_names, "t(s)", "u(N*m)", "joint_efforts_vs_t", directory=directory, log_name=log_name, colors=['r', 'b', 'g', 'y', 'k', 'brown', 'pink', 'grey'])
> 
> def consrtuct_plot_datum_pair_for_gt_and_est_vs_time(t, gt, est, title, ylabel):
> ```

typo in construct


<!-- Sent from Reviewable.io -->

2022-09-01 18:19 UTC, HaoxiangYou reviewed
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313)* status: all files reviewed, 20 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 51 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xclmh50NueXd5o9P1:-N9XwohC75VL_f7ESGMl:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L51)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Try to avoid hardcoding the size of the robot position/velocity vectors. Drake has a method that gets the number of positions/velocities `self.plant.num_positions()` and `self.plant.num_velocities()`
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 66 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XdODp5m78KTZapgW8:-N9XwxwGCK5baKzOLZvO:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L66)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

method names should use the same naming convention, so to be like the other methods it should be `draw_pose(self, q)`
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 69 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XdcLs3G7biLiOC5sy:-N9XsnEJ2h3_XHTxGnK-:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L69)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Small comment, but conventionally methods with the word `get` in them are for returning member variables. If the method is setting member variables, it usually has `set` in its name. So this should be `set_spring_stiffness`
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 72 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XdvMB4QDPry7SnYXg:-N9Xx2WcAyzL_mqoYZo-:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L72)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

this method should be `set_damping`
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 75 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xdy1L7dVnbWqbXSfB:-N9Xx8bK6wPWd90tC-l9:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L75)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

also here, it should be `set_spring_offset`
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 84 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xe5WD3sKR2ygjdRxX:-N9XxT3GBuerUAU3aXn6:buy1fz0) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L84)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

what does this function do? It looks like integration but not quite. If a function's purpose isn't obvious, add a comment explaining the function.
</blockquote></details>

Done. It was supposed to do integration. There are errors in calculating the new v (missing v_dot). The function is not used currently,  and deleted
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 129 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xeo1S3urrGzn0nKiC:-N9Y0GaIAIcgwWSf023M:b-9jh5n9) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L129)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Are these values consistent between logs? Do they need to be hardcoded? If so, can we store the hardcoded values in a separate file along with the log that was used to generate the values?
</blockquote></details>

Done, the value is put into a yaml file. The log is in google drive, whose link is in the comment of yaml file. The values are similar between logs
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 165 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XesNtE5WUq1WV0pbl:-N9b2VRs0bbyRoJ6IcVE:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L165)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

again, avoid hardcoding matrix shapes if possible.
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 254 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XfFb06zTu7xM1MDxS:-N9Y1PbT2wv0BXseq2qx:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L254)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

small comment, try to not name the list of intermediate variables the same name as each individual element in the list.
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 280 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9XfY175_SLQIUVFXwG:-N9Y5MEMBd2g4n_dDIBS:bik3ls9) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L280)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

This does seems like not the most efficient way to write this function.
</blockquote></details>

Done. The function originally can also take simulation data which include ground truth contact information for test purposes.(Make sure the codes work)  Now the redundant codes and tests are deleted. 
___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 343 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xfll39wXENKJRpfv9:-N9Y9N006Aai6PDe_3fr:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L343)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

the function of this matrix is not clear without comments
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/data_processor.py` line 7 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xi-2q1zM7uJRwzYwh:-N9hYkFo70OTVCfnknT6:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/data_processor.py#L7)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

Name should be more specific. this is not a general data processor.
</blockquote></details>

Done.
___
*[`bindings/pydairlib/analysis/residual_analysis/data_processor.py` line 12 at r1](https://reviewable.io/reviews/dairlab/dairlib/313#-N9Xhqz72x_bIkb-V_7S:-N9YAIdvCg9BC7Jc5Mmy:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/f672994cde355e424908483b7ec4a69a6489327f/bindings/pydairlib/analysis/residual_analysis/data_processor.py#L12)):*
< [...]

2022-09-01 20:43 UTC, yangwill requested changes
Looks much better! Can we add a script/function that computes how bad the model is for a particular log? That would be helpful for comparing walking vs running motions

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313#-:-NAumYci5GPbo9jZQbtl:b-2a08hj)* status: all files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta and @HaoxiangYou)

___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 54 at r4](https://reviewable.io/reviews/dairlab/dairlib/313#-NAumSXHDE3qO3JwBu3g:-NAumSXHDE3qO3JwBu3h:b-h3t28r) ([raw file](https://github.com/dairlab/dairlib/blob/9926fdb7f168525dc83430229b7a9f89ce10844b/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L54)):*
> ```Python
> 
>         # Initial other parameters
>         self.piecewice_linear_spring_paras = load(io.open(self.piecewice_linear_spring_config,"r"), Loader=Loader)
> ```

very small nitpick, the abbreviation should be `params` instead of `paras`


<!-- Sent from Reviewable.io -->

2022-09-08 15:54 UTC, HaoxiangYou reviewed
Done. 

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313#-:-NBSnk7EDrf1i3yEbx-E:bs7wumx)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @Brian-Acosta and @yangwill)

___
*[`bindings/pydairlib/analysis/residual_analysis/cassie_model.py` line 54 at r4](https://reviewable.io/reviews/dairlab/dairlib/313#-NAumSXHDE3qO3JwBu3g:-NBSniMU6BVgrPadQnqh:b-896fix) ([raw file](https://github.com/dairlab/dairlib/blob/9926fdb7f168525dc83430229b7a9f89ce10844b/bindings/pydairlib/analysis/residual_analysis/cassie_model.py#L54)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

very small nitpick, the abbreviation should be `params` instead of `paras`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-15 15:21 UTC, yangwill requested changes
Looks good except for the small comments I added, I ran the test script on a log of simulated data and still got large residuals. Is this expected? 

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313#-:-NC0fDkS-MDLvuyWfXpA:bckbx9x)* status: all files reviewed, 2 unresolved discussions (waiting on @Brian-Acosta and @HaoxiangYou)

___
*[`bindings/pydairlib/analysis/process_lcm_log.py` line 20 at r5](https://reviewable.io/reviews/dairlab/dairlib/313#-NC0exNe0K1Wv0ySxKfL:-NC0exNe0K1Wv0ySxKfM:b-phjjtn) ([raw file](https://github.com/dairlab/dairlib/blob/fffdfacd55b0ea4238b1ca66db0c972e46a3d9b1/bindings/pydairlib/analysis/process_lcm_log.py#L20)):*
> ```Python
>     lcm_log.seek(0)
>     first_timestamp = lcm_log.read_next_event().timestamp
>     start_timestamp = int(first_timestamp + start_time * 1e6)
> ```

I don't see why rounding to the nearest int is necessary
___
*[`bindings/pydairlib/analysis/residual_analysis/residual_processor.py` line 1 at r5](https://reviewable.io/reviews/dairlab/dairlib/313#-NC0dmxQ1wRNQVuOVZHb:-NC0dmxQ1wRNQVuOVZHc:bz6db53) ([raw file](https://github.com/dairlab/dairlib/blob/fffdfacd55b0ea4238b1ca66db0c972e46a3d9b1/bindings/pydairlib/analysis/residual_analysis/residual_processor.py#L1)):*
> ```Python
> from concurrent.futures import BrokenExecutor
> ```

what is this library?



_Code quote:_
```Python
Broken
```


<!-- Sent from Reviewable.io -->

2022-09-15 18:45 UTC, HaoxiangYou reviewed
Do some experiments, the residual on the hip yaw and ankle spring can be affected by the location where the contact exactly happens. If the exact position is given, then the residual of this point can be fixed, however, for the hardware test, we don't know where the contact happens, we assume the mid points of the toes are contact points 

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313#-:-NC1SGAU-OEUQAEoPsd6:bxodyny)* status: 18 of 19 files reviewed, 2 unresolved discussions (waiting on @Brian-Acosta and @yangwill)

___
*[`bindings/pydairlib/analysis/process_lcm_log.py` line 20 at r5](https://reviewable.io/reviews/dairlab/dairlib/313#-NC0exNe0K1Wv0ySxKfL:-NC0sXSzBhTESOn-kOhJ:be7xyq) ([raw file](https://github.com/dairlab/dairlib/blob/fffdfacd55b0ea4238b1ca66db0c972e46a3d9b1/bindings/pydairlib/analysis/process_lcm_log.py#L20)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

I don't see why rounding to the nearest int is necessary
</blockquote></details>

For my new laptop, I am not sure if it's python version or the lcm version, that lcm_log. seek method require an int, while if not forced to type convert, it through a traceback
___
*[`bindings/pydairlib/analysis/residual_analysis/residual_processor.py` line 1 at r5](https://reviewable.io/reviews/dairlab/dairlib/313#-NC0dmxQ1wRNQVuOVZHb:-NC0sLvj7_fzvdChIFeM:bakgqcp) ([raw file](https://github.com/dairlab/dairlib/blob/fffdfacd55b0ea4238b1ca66db0c972e46a3d9b1/bindings/pydairlib/analysis/residual_analysis/residual_processor.py#L1)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

what is this library?
</blockquote></details>

Done, a mis-included library by code auto-completion 


<!-- Sent from Reviewable.io -->

2022-09-15 19:23 UTC, yangwill approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/dairlab/dairlib/313#-:-NC1afnK9XbFFxUxrMpM:bnfp4nl)* status: 18 of 19 files reviewed, all discussions resolved (waiting on @Brian-Acosta and @yangwill)



<!-- Sent from Reviewable.io -->

2022-09-19 13:29 UTC, merged