adding support for model instances in our common utils functions
DAIRLab/dairlib pull request #353
Opened 2023-11-06 18:54 UTC by yangwill

2023-11-13 21:22 UTC, Brian-Acosta requested changes
BTW CI says there are build (linker) errors. 

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/353#-:-Nj9SFEO45IU2gXSuLy9:b-n7lh4l)* status: all files reviewed, 16 unresolved discussions (waiting on @yangwill)

___
*[`multibody/multibody_utils.h` line 83 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9U-R36N5EolZAKBwW:-Nj9U-R36N5EolZAKBwX:bf70eqz) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.h#L83)):*
> ```objc
>     const drake::multibody::MultibodyPlant<T>& plant);
> 
> /// Given a MultibodyPlant, builds a map from position name to position index
> ```

Can you use this comment to explain the difference between the two function signatures? Or better yet, can we make this one function with std::optional<ModelInstanceIndex> defaulting to empty?  
___
*[`multibody/multibody_utils.h` line 95 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9Sx7oAoBZil3B7qmY:-Nj9Sx7oAoBZil3B7qmZ:bi43iia) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.h#L95)):*
> ```objc
> 
> 
> /// Given a MultiBodyTree, builds a map from velocity name to velocity index
> ```

nit - comment should say MultibodyPlant
___
*[`multibody/multibody_utils.cc` line 155 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9T7l94O1aldzGnF_s:-Nj9T7l94O1aldzGnF_t:bgxxm36) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L155)):*
> ```cpp
>   if (show_ground) {
>     //    plant->RegisterVisualGeometry(plant->world_body(), X_WG, HalfSpace(),
>     //                                  "visual");
> ```

un-comment this 
___
*[`multibody/multibody_utils.cc` line 205 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9TSDIAqDGkrwG2OXQ:-Nj9TSDIAqDGkrwG2OXR:b8p3q2f) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L205)):*
> ```cpp
>   }
> 
>   // TODO: once RBT fully deprecated, this block can likely be removed, using
> ```

nit - while we're here, this comment doesn't seem relevant anymore 
___
*[`multibody/multibody_utils.cc` line 208 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9TJlF1H7y80uX7Xyw:-Nj9TJlF1H7y80uX7Xyx:bhes4aa) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L208)):*
> ```cpp
>   // default coordinate names from Drake.
>   auto floating_bodies = plant.GetFloatingBaseBodies();
>   //  DRAKE_THROW_UNLESS(floating_bodies.size() <= 1);
> ```

Remove dead code
___
*[`multibody/multibody_utils.cc` line 213 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9TgS4-dQdHuoqZ40w:-Nj9TgS4-dQdHuoqZ40x:b7cs3b0) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L213)):*
> ```cpp
>     DRAKE_ASSERT(body.has_quaternion_dofs());
>     int start = body.floating_positions_start();
>     // should be body.name() once RBT is deprecated
> ```

nit - same with this comment
___
*[`multibody/multibody_utils.cc` line 274 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9Tnrb49z7G3mTiTDE:-Nj9Tnrb49z7G3mTiTDF:bmsxo5c) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L274)):*
> ```cpp
> 
>   // TODO: once RBT fully deprecated, this block can likely be removed, using
>   // default coordinate names from Drake.
> ```

nit - once again
___
*[`multibody/multibody_utils.cc` line 279 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9TqkC2hI-3UZQ8qPG:-Nj9TqkC2hI-3UZQ8qPH:bb7od0r) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L279)):*
> ```cpp
>     DRAKE_ASSERT(body.has_quaternion_dofs());
>     int start = body.floating_positions_start();
>     // should be body.name() once RBT is deprecated
> ```

same
___
*[`multibody/multibody_utils.cc` line 340 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9UQr31t1CEqQDB8oI:-Nj9UQr4AIYqkIQulsGN:bhes4aa) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L340)):*
> ```cpp
>   auto floating_bodies = plant.GetFloatingBaseBodies();
>   // Remove throw once RBT deprecated
>   //  DRAKE_THROW_UNLESS(floating_bodies.size() <= 1);
> ```

Remove dead code
___
*[`multibody/multibody_utils.cc` line 409 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9V5FZDnoRUmDInHGx:-Nj9V5FZDnoRUmDInHGy:b-u9p8mw) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L409)):*
> ```cpp
>   }
> 
>   // Remove throw once RBT deprecated
> ```

remove comment
___
*[`multibody/multibody_utils.cc` line 414 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9VAS-03qlnQSeP7E2:-Nj9VAS-03qlnQSeP7E3:b-u9p8mw) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L414)):*
> ```cpp
>     int start = body.floating_velocities_start() - plant.num_positions();
>     std::string name =
>         body.name();  // should be body.name() once RBT is deprecated
> ```

remove comment
___
*[`multibody/multipose_visualizer.cc` line 3 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9VRdoDfdV7Q96AkdR:-Nj9VRdoDfdV7Q96AkdS:b-hxobvd) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multipose_visualizer.cc#L3)):*
> ```cpp
> #include "multibody/multipose_visualizer.h"
> 
> #include <iostream>
> ```

is iostream necessary? 
___
*[`multibody/multipose_visualizer.cc` line 6 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9V_-K9bPH_eUwEt_V:-Nj9V_-LAKRsk0_SKJct:b-fiev0d) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multipose_visualizer.cc#L6)):*
> ```cpp
> 
> #include "drake/geometry/drake_visualizer.h"
> #include "drake/geometry/meshcat_visualizer_params.h"
> ```

do we need meshcat_visualizer_params or just meshcat_visualizer? 
___
*[`multibody/visualization_utils.cc` line 7 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9W_aYDej8L-Nw24bX:-Nj9W_aYDej8L-Nw24bY:b-nz5z9a) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/visualization_utils.cc#L7)):*
> ```cpp
> #include "systems/primitives/subvector_pass_through.h"
> #include "drake/geometry/drake_visualizer.h"
> #include "drake/geometry/meshcat_visualizer.h"
> ```

Meshcat is included but not used?
@yangwill Since you're the only one who uses trajectory optimization currently,  would you be willing to just remove drake visualizer from trajectory visualization tools in favor of meshcat?
___
*[`systems/robot_lcm_systems.h` line 34 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9YGB1-KWlskAVXsds:-Nj9YGB1-KWlskAVXsdt:b-47r8dc) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/systems/robot_lcm_systems.h#L34)):*
> ```objc
>   explicit RobotOutputReceiver(
>       const drake::multibody::MultibodyPlant<double>& plant,
>       drake::multibody::ModelInstanceIndex model_instance);
> ```

Similarly to above, can we get away with one constructor which takes a std::optional<ModelInstanceIndex>
___
*[`systems/robot_lcm_systems.h` line 169 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9Yv435GLyblgeapU1:-Nj9Yv435GLyblgeapU2:batupum) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/systems/robot_lcm_systems.h#L169)):*
> ```objc
>     std::string state_channel, double publish_rate,
>     drake::multibody::ModelInstanceIndex model_instance_ind [...]

2023-11-13 21:46 UTC, yangwill reviewed
Yep, probably missed some functions when copying over files, will fix in next revision

> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/353#-:-Nj9dc-y6-Xnk1wciRzq:bkyb0hw)* status: all files reviewed, 16 unresolved discussions (waiting on @Brian-Acosta)

___
*[`multibody/multibody_utils.h` line 83 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9U-R36N5EolZAKBwW:-Nj9c1ZTA3N5NejZWA6I:b-6ps69y) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.h#L83)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Can you use this comment to explain the difference between the two function signatures? Or better yet, can we make this one function with std::optional<ModelInstanceIndex> defaulting to empty?
</blockquote></details>

this is because `default_model_instance` [link to doc](https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1multibody.html#a786cd667a624e8cbd915cf50b02c8792) returns only the tree elements without an explicit model instance, whereas we sometimes want to use it to get all tree elements regardless of how they were added (calling MultibodyPlant functions with no model instance).

Drake also has this issue
i.e. `num_positions()` has no equivalent `num_positions(ModelInstanceIndex)`

If you have a solution, let me know - i agree it's annoying/ugly.


<!-- Sent from Reviewable.io -->

2023-11-13 21:58 UTC, Brian-Acosta requested changes
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/353)* status: all files reviewed, 16 unresolved discussions (waiting on @yangwill)

___
*[`multibody/multibody_utils.h` line 83 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9U-R36N5EolZAKBwW:-Nj9fuIeDKOmaJjVPWQ9:b-ylfn1n) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.h#L83)):*
<details><summary><i>Previously, yangwill (William Yang) wrote…</i></summary><blockquote>

this is because `default_model_instance` [link to doc](https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1multibody.html#a786cd667a624e8cbd915cf50b02c8792) returns only the tree elements without an explicit model instance, whereas we sometimes want to use it to get all tree elements regardless of how they were added (calling MultibodyPlant functions with no model instance).

Drake also has this issue
i.e. `num_positions()` has no equivalent `num_positions(ModelInstanceIndex)`

If you have a solution, let me know - i agree it's annoying/ugly.
</blockquote></details>

Sorry I'm not sure my suggestion was clear. My suggestion was for the function signature to be something like:



_Code snippet:_
```objc
template <typename T>
std::map<std::string, int> MakeNameToPositionsMap(
    const drake::multibody::MultibodyPlant<T>& plant,
    std::optional<drake::multibody::ModelInstanceIndex> model_instance_index = std::nullopt);
```


<!-- Sent from Reviewable.io -->

2023-11-14 15:35 UTC, yangwill reviewed
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/353)* status: all files reviewed, 12 unresolved discussions (waiting on @Brian-Acosta)

___
*[`multibody/multibody_utils.h` line 83 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9U-R36N5EolZAKBwW:-NjDT1uS8QaC6z2W8iiX:blget8s) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.h#L83)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Sorry I'm not sure my suggestion was clear. My suggestion was for the function signature to be something like:
</blockquote></details>

as mentioned in f2f, it's not trivial as drake doesn't have a default model instance index that behaves as is calling without a model instance index, so we would have to have an if statement accompanying any function calls that might use a model instance index
___
*[`multibody/multibody_utils.cc` line 155 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9T7l94O1aldzGnF_s:-NjDQ2SDBQx4ZEdojJTr:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L155)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

un-comment this
</blockquote></details>

Done.
___
*[`multibody/multibody_utils.cc` line 208 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9TJlF1H7y80uX7Xyw:-NjDQ5GE30gfwwXMhSHQ:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L208)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.
___
*[`multibody/multibody_utils.cc` line 279 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9TqkC2hI-3UZQ8qPG:-NjDQ6ro48C-FgSwKCuJ:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L279)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`multibody/multibody_utils.cc` line 340 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9UQr31t1CEqQDB8oI:-NjDQ7LSClYQPL1uoM0S:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L340)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.
___
*[`multibody/multibody_utils.cc` line 409 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9V5FZDnoRUmDInHGx:-NjDQ82RCCO3IC6SK5Qn:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L409)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.
___
*[`multibody/multibody_utils.cc` line 414 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9VAS-03qlnQSeP7E2:-NjDQ8b9BPfdfyOVRhug:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multibody_utils.cc#L414)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.
___
*[`multibody/multipose_visualizer.cc` line 3 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9VRdoDfdV7Q96AkdR:-NjDQCFp7ZFWJGenZM6i:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multipose_visualizer.cc#L3)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

is iostream necessary?
</blockquote></details>

Done.
___
*[`multibody/multipose_visualizer.cc` line 6 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9V_-K9bPH_eUwEt_V:-NjDQEIo6KLrs4dqP9Q0:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/multipose_visualizer.cc#L6)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

do we need meshcat_visualizer_params or just meshcat_visualizer?
</blockquote></details>

Done.
___
*[`multibody/visualization_utils.cc` line 7 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9W_aYDej8L-Nw24bX:-NjDQoA_4tVoSqdYRWlG:bskkuf2) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/multibody/visualization_utils.cc#L7)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Meshcat is included but not used?
@yangwill Since you're the only one who uses trajectory optimization currently,  would you be willing to just remove drake visualizer from trajectory visualization tools in favor of meshcat?
</blockquote></details>

yep, will do. actually will remove all references to drake visualizer and meshcat visualizer in this file as we can choose the visualizer by attaching the scenegraph outside of this function.
___
*[`systems/robot_lcm_systems.h` line 34 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9YGB1-KWlskAVXsds:-NjDSG8g0M4McI_ahztw:b-e1j21l) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/systems/robot_lcm_systems.h#L34)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Similarly to above, can we get away with one constructor which takes a std::optional<ModelInstanceIndex>
</blockquote></details>

i dont think it's trivial to condense the two functions with optional, drake `multibody_plant.cc` also has separate implementations for with and without a model instance index 
___
*[`systems/robot_lcm_systems.h` line 169 at r1](https://reviewable.io/reviews/DAIRLab/dairlib/353#-Nj9Yv435GLyblgeapU1:-NjDSzkqC5Meu3Qv_ynh:b-896fix) ([raw file](https://github.com/DAIRLab/dairlib/blob/8dcb549706b49306e2e2db6bf586bf994f4ec4e6/systems/robot_lcm_systems.h#L169)):*
<details><summary><i>Previously, Brian-Acosta (Brian Acosta) wrote…</i></summary><blockquote>

Same here re: one function signature
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-14 15:46 UTC, Brian-Acosta approved these changes
LGTM (assuming CI passes)

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/353#-:-NjDVckN9HAfQJc-faoo:bgzlwhy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangwill)



<!-- Sent from Reviewable.io -->

2023-11-14 16:03 UTC, yangwill reviewed
Oops, will need another revision, have some compile errors and after fixing those also have some examples not working properly.

> *[Reviewable](https://reviewable.io/reviews/DAIRLab/dairlib/353#-:-NjDZdCH4EvJIPG61Z6h:b-7hnan2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangwill)



<!-- Sent from Reviewable.io -->

2026-07-18 15:34 UTC, merged